[package]
name = "hopers-bet"
version = "0.1.0"
authors = [ "Deliver DAO" ]
edition = "2018"

[dependencies]
cosmwasm-std = { version = "1.1.0" }
cosmwasm-storage = { version = "1.1.0" }
cosmwasm-schema = { version = "1.1.0" }
cw-storage-plus = "0.16.0"
thiserror = { version = "1.0.26" }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0" }
